title: "Cube Algorithms"
description: "collection of algs"
url: "https://oixc.github.io"
baseurl: ""

collections:
  algs:
    output: true
    permalink: /:collection/:path

exclude: ["README.md", "LICENSE"]
